#!/bin/bash

status=0

if [ "$FEPXROOT" == "" ]
then
  echo "Environment variable FEPXROOT not set.  You need to set it to FEPX's root directory."
  exit -1
fi

EDITOR=`git config --global core.editor`
if [ "$EDITOR" == "" ]
then
  EDITOR="vi"
fi

git commit $1
status="$?"

date=`date +"%d %b %G"`
tag=`git describe | grep v1.0.0 | awk -F- '{print $1}'`
id=` git describe | grep v1.0.0 | awk -F- '{print $3}'`

if [ "$tag" == "" ]
then
  echo "Failed to find start tag."
  exit -1
fi

branch=`git status | head -1 | awk '{print $3}'`

if [ "$branch" == "main" ]
then
  version="$tag-$id"
else
  version="$tag-$id-$branch"
fi

if [ "$status" != "0" ]
then
  echo Version $version
  exit $status
fi

sed -i "1s/.*/New in $version ($date):/g" $FEPXROOT/VERSIONS
$EDITOR $FEPXROOT/VERSIONS
version2=`echo $version | sed -e "s/_/@&/g"`
sed -i "1,100s/@set FEPX_VERSION.*/@set FEPX_VERSION $version2/g" $FEPXROOT/doc/texinfo/version.texi

sed -i "1,100s/Version.*/Version $version'/g" $FEPXROOT/src//fepx.f90
git add $FEPXROOT/VERSIONS $FEPXROOT/doc/texinfo/version.texi $FEPXROOT/src/CMakeLists.txt $FEPXROOT/src/fepx.f90
git commit --amend --no-edit > /dev/null
status="$?"

if [ "$status" == "0" ]
then
  echo "Updated version to $version."
else
  echo "Failed to update version to $version.  Something nasty happened:"
  git status
  exit 1
fi

exit 0
